# 1. Server Config
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

# 2. Spring Config
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url:
    username:
    password:

# 3. Mybatis
mybatis:
  type-aliases-package: com.mc.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 4. Log Level
logging:
  level:
    root: info

# 5. App
app:
  dir:
    imgdir:   # 화면 출력 용
    uploadimgdir:     # 파일 Write 용

